name: "ssd_mobilenet_v3"
platform: "pytorch_libtorch"
max_batch_size : 1
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 3, 320, 320 ]
    }
]
output [
{
name: "boxes__0"
data_type: TYPE_FP32
dims: [-1,]
},
{
name: "scores__1"
data_type: TYPE_FP32
dims: [ -1 ]
},
{
name: "labels__2"
data_type: TYPE_INT64
dims: [ 91 ]
}
]